# Generated by Django 3.2 on 2022-06-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_default_user_userprofile_user'),
        ('products', '0003_auto_20220526_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourites',
            field=models.ManyToManyField(default=None, related_name='favourite', to='profiles.UserProfile'),
        ),
    ]
